export const DIMENSIONS = {
     PLATFORM_WIDTH: 80,
     PLATFORM_HEIGHT: 5,
     DOODLE_WIDTH: 40,
     DOODLE_HEIGHT: 70,
     MAX_SEPARATION_SPACE: 115,
};

export const DISPLACEMENT = {
     GRAVITY: 0.5,
     JUMP_STRENGTH: -15,
};
